### ISSUE TITLE
PNW-ML in SeisBench

### ISSUE THREAD

**Issue by yetinam** [niyiyu/PNW-ML#1]
Hi @niyiyu ,

I've read your preprint and it's really an amazing dataset you have compiled. I was wondering, if you'd be interested in making your dataset (and potentially your picker) available directly through SeisBench. I could also offer to host a mirrored version on our server.

Let me know if you're interested in this. I think regarding code it's a pretty quick job to integrate it. I think it would be great to have the dataset available directly through SeisBench.

**Comment by niyiyu** [comment]
hi @yetinam ,

Thanks for proposing hosting the data. Yes I am very happy seisbench could take this as one of embedded dataset. The data is originally in sbd format so the mirroring should be pretty straight forward. I will test it with the latest seisbench version and create a PR soon. Hopefully next week.

Cheers,
Yiyu

**Comment by yetinam** [comment]
Great! If you need inspiration for the PR, the [OBS dataset](https://github.com/seisbench/seisbench/blob/main/seisbench/data/obs.py) might be a good orientation. If the dataset does not use chunks, the respective functions are clearly not necessary. If we mirror the data to our server, even the `_download_dataset` function is not required.

**Comment by niyiyu** [comment]
Hi @yetinam,

Just created the PR in SeisBench repo: https://github.com/seisbench/seisbench/pull/199
Feel free to review it : )
