### ISSUE TITLE
Drawing figures

### ISSUE THREAD

**Issue by senli1073** [niyiyu/PNW-ML#2]
Hi @niyiyu ,

I've read your paper and tried to do some tests on this dataset using my model.

Figure 3 named "Locations of the events included in the ComCat dataset" in the paper is pretty cool, but I'm having trouble achieving this effect when using PyGMT. Is it possible to provide plotting parameters?

**Comment by niyiyu** [comment]
Hi @senli1073 ,

Thanks for checking this dateset. Would you mind provide an email and I am happy to send the script. Sending one request to niyiyu@uw.edu also works : )

Yiyu
